### ISSUE TITLE
'couch' has no method 'request'

### ISSUE THREAD

**Issue by pradeep122** [eHealthAfrica/couchdb-configure#3]
I am unable to run couchdb-configure.  I get ```Object #<Object> has no method 'request'``` error constantly. Im using the latest version of couchdb-configure - 1.3.3 

I tried downgrading the couchdb-configure module to 1.3.2, but keep getting the same error.

```
couchdb-configure http://admin:password@localhost:5984/pop _config.json 

	/home/deepster/.npm-packages/lib/node_modules/couchdb-configure/index.js:25
	      couch.request({
	            ^
	TypeError: Object #<Object> has no method 'request'
	    at async.map.responses.reduce.memo.(anonymous function).ok (/home/deepster/.npm-packages/lib/node_modules/couchdb-configure/index.js:25:13)
	    at /home/deepster/.npm-packages/lib/node_modules/couchdb-configure/node_modules/async/lib/async.js:346:13
	    at /home/deepster/.npm-packages/lib/node_modules/couchdb-configure/node_modules/async/lib/async.js:227:13
	    at _arrayEach (/home/deepster/.npm-packages/lib/node_modules/couchdb-configure/node_modules/async/lib/async.js:78:13)
	    at _each (/home/deepster/.npm-packages/lib/node_modules/couchdb-configure/node_modules/async/lib/async.js:69:13)
	    at async.forEachOf.async.eachOf (/home/deepster/.npm-packages/lib/node_modules/couchdb-configure/node_modules/async/lib/async.js:226:9)
	    at _asyncMap (/home/deepster/.npm-packages/lib/node_modules/couchdb-configure/node_modules/async/lib/async.js:345:9
```

**Comment by jo** [comment]
You must point couchdb-configure to the root of your couchdb server, not to a database:

```sh
couchdb-configure http://admin:password@localhost:5984 _config.json 
```

I agree that the error is very poor, I'll open another issue for that.

**Comment by pradeep122** [comment]
thanks @jo ,appreciate the quick response.

works like a charm now
