### ISSUE TITLE
Improved error messages

### ISSUE THREAD

**Issue by tohagan** [eHealthAfrica/couchdb-configure#5]
I'm getting this exception when I call couchdb-bootstrap with a config.
I've never got couchdb-bootstrap to work it always fails with this exception.

C:\nvm\v0.10.32\node_modules\couchdb-bootstrap\node_modules\couchdb-configure\index.js:25                                        
      couch.request({                                                                                                            
            ^                                                                                                                    
TypeError: Object #<Object> has no method 'request'                                                                              
    at async.map.responses.reduce.memo.(anonymous function).ok (C:\nvm\v0.10.32\node_modules\couchdb-bootstrap\node_modules\couch
db-configure\index.js:25:13)                                                                                                     
    at C:\nvm\v0.10.32\node_modules\couchdb-bootstrap\node_modules\async\lib\async.js:358:13                                     
    at C:\nvm\v0.10.32\node_modules\couchdb-bootstrap\node_modules\async\lib\async.js:239:13                                     
    at _arrayEach (C:\nvm\v0.10.32\node_modules\couchdb-bootstrap\node_modules\async\lib\async.js:91:13)                         
    at _each (C:\nvm\v0.10.32\node_modules\couchdb-bootstrap\node_modules\async\lib\async.js:82:13)                              
    at async.forEachOf.async.eachOf (C:\nvm\v0.10.32\node_modules\couchdb-bootstrap\node_modules\async\lib\async.js:238:9)       
    at _asyncMap (C:\nvm\v0.10.32\node_modules\couchdb-bootstrap\node_modules\async\lib\async.js:357:9)                          
    at Object.map (C:\nvm\v0.10.32\node_modules\couchdb-bootstrap\node_modules\async\lib\async.js:340:20)                        
    at C:\nvm\v0.10.32\node_modules\couchdb-bootstrap\node_modules\couchdb-configure\index.js:24:11                              
    at C:\nvm\v0.10.32\node_modules\couchdb-bootstrap\node_modules\couchdb-configure\node_modules\couchdb-compile\index.js:85:5

**Comment by tohagan** [comment]
OK ... Fix ..I that this was trigger by using an invalid URL that include the database name.
Hence nano() returned a database object rather than a server object.

**Comment by jo** [comment]
Better errors are absolutely needed here!

**Comment by tohagan** [comment]
Thanks!
